spring:
  application:
    name: order-service
  config:
    import: configserver:http://localhost:8080

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: refresh


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # you can give ip address also in default zone   http://10.0.0.191:8761/eureka
    register-with-eureka: true